// Lucide icons by kebab-case name, matching the prototype's <et-i n s c>.
// Only the icons the app references are bundled; add new names to this list.
import {
  Activity,
  AlarmClock,
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Ban,
  BatteryLow,
  Beef,
  Bike,
  Book,
  BookHeart,
  BookOpen,
  Bookmark,
  BookmarkCheck,
  Brain,
  Briefcase,
  CakeSlice,
  Calendar,
  CalendarX,
  Cat,
  Check,
  CheckCheck,
  Cherry,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  Clapperboard,
  Clock,
  CloudFog,
  CloudLightning,
  CloudOff,
  Compass,
  CookingPot,
  Cpu,
  Crown,
  Ellipsis,
  Eraser,
  Eye,
  EyeOff,
  Feather,
  FilePen,
  FileStack,
  FileText,
  FileWarning,
  Fish,
  Flag,
  Flame,
  GraduationCap,
  Headphones,
  Heart,
  HeartCrack,
  HeartHandshake,
  Highlighter,
  History,
  Hourglass,
  House,
  Image,
  Infinity,
  Landmark,
  Layers,
  LayoutGrid,
  Leaf,
  Library,
  Lightbulb,
  Lock,
  LockKeyhole,
  LogOut,
  Map,
  MessageCircle,
  MessageCircleHeart,
  MessagesSquare,
  Moon,
  Mountain,
  Music,
  Palette,
  Pencil,
  Plane,
  Play,
  Plus,
  Pointer,
  Quote,
  RefreshCw,
  Repeat,
  Salad,
  Scale,
  Scroll,
  ScrollText,
  Search,
  Send,
  Shell,
  ShieldCheck,
  ShoppingBag,
  Signpost,
  Smartphone,
  Smile,
  Soup,
  Sparkle,
  Sparkles,
  Split,
  Sprout,
  Star,
  Stethoscope,
  Store,
  Sun,
  Swords,
  Text,
  Timer,
  Trash2,
  Trees,
  TrendingUp,
  TriangleAlert,
  Upload,
  User,
  UserRound,
  UserRoundX,
  Users,
  UsersRound,
  Wallet,
  Waves,
  Wheat,
  WifiOff,
  Wind,
  X,
} from "lucide-react";

const ICONS = {
  "activity": Activity,
  "alarm-clock": AlarmClock,
  "archive": Archive,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "arrow-up-right": ArrowUpRight,
  "ban": Ban,
  "battery-low": BatteryLow,
  "beef": Beef,
  "bike": Bike,
  "book": Book,
  "book-heart": BookHeart,
  "book-open": BookOpen,
  "bookmark": Bookmark,
  "bookmark-check": BookmarkCheck,
  "brain": Brain,
  "briefcase": Briefcase,
  "cake-slice": CakeSlice,
  "calendar": Calendar,
  "calendar-x": CalendarX,
  "cat": Cat,
  "check": Check,
  "check-check": CheckCheck,
  "cherry": Cherry,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  "clapperboard": Clapperboard,
  "clock": Clock,
  "cloud-fog": CloudFog,
  "cloud-lightning": CloudLightning,
  "cloud-off": CloudOff,
  "compass": Compass,
  "cooking-pot": CookingPot,
  "cpu": Cpu,
  "crown": Crown,
  "ellipsis": Ellipsis,
  "eraser": Eraser,
  "eye": Eye,
  "eye-off": EyeOff,
  "feather": Feather,
  "file-pen": FilePen,
  "file-stack": FileStack,
  "file-text": FileText,
  "file-warning": FileWarning,
  "fish": Fish,
  "flag": Flag,
  "flame": Flame,
  "graduation-cap": GraduationCap,
  "headphones": Headphones,
  "heart": Heart,
  "heart-crack": HeartCrack,
  "heart-handshake": HeartHandshake,
  "highlighter": Highlighter,
  "history": History,
  "hourglass": Hourglass,
  "house": House,
  "image": Image,
  "infinity": Infinity,
  "landmark": Landmark,
  "layers": Layers,
  "layout-grid": LayoutGrid,
  "leaf": Leaf,
  "library": Library,
  "lightbulb": Lightbulb,
  "lock": Lock,
  "lock-keyhole": LockKeyhole,
  "log-out": LogOut,
  "map": Map,
  "message-circle": MessageCircle,
  "message-circle-heart": MessageCircleHeart,
  "messages-square": MessagesSquare,
  "moon": Moon,
  "mountain": Mountain,
  "music": Music,
  "palette": Palette,
  "pencil": Pencil,
  "plane": Plane,
  "play": Play,
  "plus": Plus,
  "pointer": Pointer,
  "quote": Quote,
  "refresh-cw": RefreshCw,
  "repeat": Repeat,
  "salad": Salad,
  "scale": Scale,
  "scroll": Scroll,
  "scroll-text": ScrollText,
  "search": Search,
  "send": Send,
  "shell": Shell,
  "shield-check": ShieldCheck,
  "shopping-bag": ShoppingBag,
  "signpost": Signpost,
  "smartphone": Smartphone,
  "smile": Smile,
  "soup": Soup,
  "sparkle": Sparkle,
  "sparkles": Sparkles,
  "split": Split,
  "sprout": Sprout,
  "star": Star,
  "stethoscope": Stethoscope,
  "store": Store,
  "sun": Sun,
  "swords": Swords,
  "text": Text,
  "timer": Timer,
  "trash-2": Trash2,
  "trees": Trees,
  "trending-up": TrendingUp,
  "triangle-alert": TriangleAlert,
  "upload": Upload,
  "user": User,
  "user-round": UserRound,
  "user-round-x": UserRoundX,
  "users": Users,
  "users-round": UsersRound,
  "wallet": Wallet,
  "waves": Waves,
  "wheat": Wheat,
  "wifi-off": WifiOff,
  "wind": Wind,
  "x": X,
};

export function Icon({ n = "circle", s = 18, c }) {
  const C = ICONS[n];
  if (!C) {
    if (import.meta.env.DEV) console.warn(`[Icon] "${n}" is not registered in Icon.jsx`);
    return <span aria-hidden="true" style={{ display: "inline-block", flex: "none", width: +s, height: +s }} />;
  }
  return <C size={+s} color={c || "currentColor"} aria-hidden="true" style={{ display: "inline-block", flex: "none" }} />;
}
